FROM python:3

ENV PYTHONUNBUFFERED 1

RUN mkdir /home/docker/cloud -p
RUN mkdir /home/docker/cloud/run -p
WORKDIR /home/docker/cloud

COPY . /home/docker/cloud

COPY requirements.txt /home/docker/cloud/
COPY uwsgi.ini /home/docker/cloud/
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
