# Generated by Django 3.0.7 on 2020-06-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fs.Domain', verbose_name='企业'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fs.Domain', verbose_name='企业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fs.Domain', verbose_name='企业'),
        ),
    ]
