# Generated by Django 3.0.7 on 2020-06-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_auto_20200614_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='default',
        ),
    ]
