# Generated by Django 3.0.7 on 2020-06-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0004_remove_gateway_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='caller',
        ),
    ]
