# Generated by Django 3.0.7 on 2020-06-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0005_remove_project_caller'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(null=True, verbose_name='资料结果id')),
                ('mobile', models.CharField(max_length=50, verbose_name='号码')),
                ('duration', models.IntegerField(default=0, verbose_name='接通时长')),
                ('billsec', models.IntegerField(default=0, verbose_name='通话时长')),
                ('start_time', models.DateTimeField(null=True, verbose_name='呼叫时间')),
                ('answer_time', models.DateTimeField(null=True, verbose_name='应答时间')),
                ('bridge_time', models.DateTimeField(null=True, verbose_name='接通时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='挂机时间')),
                ('hangup_cause', models.CharField(blank=True, default='', max_length=50, verbose_name='挂机原因')),
                ('hangup_source', models.CharField(blank=True, default='', max_length=50, verbose_name='挂机方')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('queue_name', models.CharField(blank=True, default='', max_length=50, verbose_name='队列')),
                ('user', models.IntegerField(null=True, verbose_name='坐席id')),
                ('status', models.IntegerField(choices=[(1, '接通'), (2, '未接通'), (3, '呼损')], default=2, verbose_name='状态')),
                ('recording', models.CharField(blank=True, default='', max_length=200, verbose_name='录音地址')),
            ],
        ),
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, unique=True, verbose_name='主键id 用来做数据关联')),
            ],
        ),
    ]
