# Generated by Django 3.0.7 on 2020-06-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_callresult_cdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='callresult',
            name='callsec',
            field=models.IntegerField(default=0, verbose_name='通话时长'),
        ),
    ]
