# Generated by Django 3.0.7 on 2020-06-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0007_callresult_callsec'),
    ]

    operations = [
        migrations.AddField(
            model_name='callresult',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='呼叫类型'),
        ),
        migrations.AlterField(
            model_name='callresult',
            name='billsec',
            field=models.IntegerField(default=0, verbose_name='接通时长'),
        ),
        migrations.AlterField(
            model_name='callresult',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='呼叫时长'),
        ),
    ]
