# Generated by Django 3.0.7 on 2020-06-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0008_auto_20200614_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='callresult',
            name='callee_id_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='被叫名'),
        ),
        migrations.AddField(
            model_name='callresult',
            name='callee_id_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='被叫号码'),
        ),
        migrations.AddField(
            model_name='callresult',
            name='caller_id_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='主叫名'),
        ),
        migrations.AddField(
            model_name='callresult',
            name='caller_id_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='主叫号码'),
        ),
    ]
